skus:
- max_budget_per_order: 16174
  max_shelf_capacity: 362
  perishability_days: 120
  safety_stock_days: 3
  sku: ASYMMETRICAL_WOOL_AND_SILK_BLEND_SWEATER
  unit_cost: 21.69
- max_budget_per_order: 10571
  max_shelf_capacity: 370
  perishability_days: 120
  safety_stock_days: 3
  sku: ASYMMETRIC_CROPPED_KNIT_SWEATER
  unit_cost: 14.54
- max_budget_per_order: 14052
  max_shelf_capacity: 148
  perishability_days: 60
  safety_stock_days: 3
  sku: BOUCL_TEXTURED_JACKET_MAN
  unit_cost: 39.62
- max_budget_per_order: 13538
  max_shelf_capacity: 182
  perishability_days: 120
  safety_stock_days: 3
  sku: CONTRASTING_COLLAR_JACKET
  unit_cost: 31.53
- max_budget_per_order: 22922
  max_shelf_capacity: 394
  perishability_days: 120
  safety_stock_days: 3
  sku: COTTON_BLEND_BOMBER_JACKET
  unit_cost: 32.77
- max_budget_per_order: 5136
  max_shelf_capacity: 158
  perishability_days: 120
  safety_stock_days: 3
  sku: COTTON_JACKET
  unit_cost: 11.81
- max_budget_per_order: 29961
  max_shelf_capacity: 232
  perishability_days: 120
  safety_stock_days: 3
  sku: DOUBLE_FACED_JACKET
  unit_cost: 55.17
- max_budget_per_order: 10635
  max_shelf_capacity: 188
  perishability_days: 90
  safety_stock_days: 3
  sku: DOUBLE_STRAP_SUEDE_SANDALS
  unit_cost: 21.87
- max_budget_per_order: 23768
  max_shelf_capacity: 424
  perishability_days: 120
  safety_stock_days: 3
  sku: FAUX_LEATHER_BOMBER_JACKET_MAN
  unit_cost: 39.82
- max_budget_per_order: 8021
  max_shelf_capacity: 198
  perishability_days: 120
  safety_stock_days: 3
  sku: FAUX_LEATHER_PUFFER_JACKET_MAN
  unit_cost: 15.73
- max_budget_per_order: 12632
  max_shelf_capacity: 318
  perishability_days: 120
  safety_stock_days: 3
  sku: GATHERED_WAIST_KNIT_SWEATER
  unit_cost: 17.44
- max_budget_per_order: 13963
  max_shelf_capacity: 184
  perishability_days: 90
  safety_stock_days: 3
  sku: HIKING_BOOTS
  unit_cost: 29.2
- max_budget_per_order: 33920
  max_shelf_capacity: 172
  perishability_days: 120
  safety_stock_days: 3
  sku: LONGLINE_QUILTED_JACKET
  unit_cost: 66.46
- max_budget_per_order: 7736
  max_shelf_capacity: 252
  perishability_days: 90
  safety_stock_days: 3
  sku: MULTIPIECED_RETRO_SNEAKERS
  unit_cost: 16.69
- max_budget_per_order: 5566
  max_shelf_capacity: 444
  perishability_days: 120
  safety_stock_days: 3
  sku: PLAID_TIE_DYE_OVERSHIRT
  unit_cost: 7.3
- max_budget_per_order: 27417
  max_shelf_capacity: 204
  perishability_days: 120
  safety_stock_days: 3
  sku: POCKET_JACKET_MAN
  unit_cost: 54.79
- max_budget_per_order: 2775
  max_shelf_capacity: 262
  perishability_days: 120
  safety_stock_days: 3
  sku: PURL_KNIT_SWEATER
  unit_cost: 5.1
- max_budget_per_order: 27832
  max_shelf_capacity: 212
  perishability_days: 120
  safety_stock_days: 3
  sku: RIB_COLLAR_JACKET_MAN
  unit_cost: 50.84
- max_budget_per_order: 9942
  max_shelf_capacity: 110
  perishability_days: 150
  safety_stock_days: 3
  sku: RIPPED_STRAIGHT_FIT_JEANS
  unit_cost: 27.57
- max_budget_per_order: 13078
  max_shelf_capacity: 90
  perishability_days: 120
  safety_stock_days: 3
  sku: SUIT_JACKET_IN_100_LINEN_MAN
  unit_cost: 43.02
